import Header from '@/components/layout/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter, Mulish, Montserrat } from 'next/font/google';
import Providers from './providers';
import Announcement from '@/components/actions/Announcement';
import Border from '@/components/layout/Border';
import Ankle from '@/components/layout/Ankle';
import Footer from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] });
const monsterrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='dark'>
      <body className={`${inter.className} ${monsterrat.className}`}>
        <Announcement />
        <Providers>
          <Header />
          <Border />
          {children}
          <Ankle />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
